// Dados mantidos manualmente. Cada site = 1 associação ou congresso.
// nivel: "A" (personalizado), "B" ou "C" (hotsite padrão), ou null (ainda não classificado)
// status: "vercel" (já migrado), "wordpress" (ainda no modelo antigo), "indefinido"
// tipo: "associacao", "congresso", ou null (a confirmar)
const SITES = [
  { slug: "76cnbot", nome: null, tipo: "congresso", nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "abih", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-abih", dominio: null, obs: "Já migrado (pasta local + projeto Vercel)" },
  { slug: "abmevec", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "abpsigero", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "abrapee", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "abravas", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "asbro", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "azab", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "cbesb", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "cbtox", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "cilamce", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "cobal27", nome: null, tipo: "congresso", nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "compos", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "conesquemas", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "conneuropsi", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "connortenordeste", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "conpe", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "cppc", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "jornada-terapia-esquema", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "opj", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "rodaporao", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "sbcs", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "sbeb", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "sben", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "sbph", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "sbtox", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "seepq", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "sepoc", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "simposiomineiro", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "smcs", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },
  { slug: "unicalce", nome: null, tipo: null, nivel: null, status: "wordpress", vercelProject: null, dominio: null, obs: "" },

  { slug: "eni", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-eni", dominio: null, obs: "" },
  { slug: "wans", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-wans", dominio: null, obs: "" },
  { slug: "iipsicogerontologia", nome: null, tipo: "congresso", nivel: null, status: "vercel", vercelProject: "sites-iipsicogerontologia", dominio: "congressopsicogerontologia2026.softaliza.com.br", obs: "" },
  { slug: "aatesp", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-aatesp", dominio: null, obs: "" },
  { slug: "sbni", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-sbni", dominio: null, obs: "" },
  { slug: "sbph2027", nome: null, tipo: "congresso", nivel: null, status: "vercel", vercelProject: "sites-sbph2027", dominio: null, obs: "Possível edição/congresso ligado a sbph — confirmar" },
  { slug: "geors", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-geors", dominio: null, obs: "" },
  { slug: "jornadapuc2026", nome: null, tipo: "congresso", nivel: null, status: "vercel", vercelProject: "sites-jornadapuc2026", dominio: null, obs: "" },
  { slug: "polodigital", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-polodigital", dominio: null, obs: "" },
  { slug: "apapesp", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-apapesp", dominio: null, obs: "" },
  { slug: "abravet", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-abravet", dominio: null, obs: "" },
  { slug: "javapsic", nome: null, tipo: null, nivel: null, status: "vercel", vercelProject: "sites-javapsic", dominio: null, obs: "" },
  { slug: "sincol2026", nome: null, tipo: "congresso", nivel: null, status: "vercel", vercelProject: "sites-sincol2026", dominio: null, obs: "" },
  { slug: "aatp", nome: null, tipo: null, nivel: "B", status: "vercel", vercelProject: "sites-aatp", dominio: "aatp.softaliza.com.br", obs: "Referência de hotsite padrão B/C citada pelo diretor" },
  { slug: "cobep2027", nome: null, tipo: "congresso", nivel: null, status: "vercel", vercelProject: "sites-cobep2027", dominio: null, obs: "" },
];
