// ============================================================================
// Dados brutos das fontes reais (CS Hub + planilha de inventário de sites).
// O merge/enriquecimento acontece em runtime, em script.js.
// ============================================================================

// --- CS Hub: tabela `associations` (clientes ativos/implantação/cancelados) ---
const ASSOCIATIONS_CRM = [
  { sigla: "AADA", nome: "Associação de Apoio e Desenvolvimento da Advocacia de Araguaína e Região", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "AARJ", nome: "Associação de Arteterapia do Rio de Janeiro", health: "saudavel", statusCrm: "ativo", mrr: 857 },
  { sigla: "AATESP", nome: "Associação de Arteterapia do Estado de São Paulo", health: "risco", statusCrm: "implantacao", mrr: 757 },
  { sigla: "AATP", nome: "Associação dos Advogados Trabalhistas de Pernambuco", health: "saudavel", statusCrm: "ativo", mrr: 386 },
  { sigla: "ABAT", nome: "Associação Brasileira de Advocacia Tributária", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "ABAV-AM", nome: "Associação Brasileira de Agências de Viagens do Amazonas", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABCVAC", nome: "Associação Brasileira de Clínicas de Vacinas", health: "risco", statusCrm: "implantacao", mrr: 657 },
  { sigla: "ABE", nome: "Associação Brasileira de Estatística", health: "atencao", statusCrm: "ativo", mrr: 750 },
  { sigla: "ABEAD", nome: "Associação Brasileira de Estudos do Álcool e outras Drogas", health: "saudavel", statusCrm: "ativo", mrr: 550 },
  { sigla: "ABIH", nome: "Associação Brasileira da Indústria de Hotéis da Paraíba", health: null, statusCrm: null, mrr: null },
  { sigla: "ABEClin", nome: "Associação Brasileira de Engenharia Clínica", health: "atencao", statusCrm: "ativo", mrr: 350 },
  { sigla: "ABEE-MT", nome: "Associação Brasileira dos Engenheiros Eletrecistas - Mato Grosso", health: "saudavel", statusCrm: "ativo", mrr: 397 },
  { sigla: "ABEMEC-SE", nome: "Associação Brasileira de Engenheiros Mecânicos e Industriais, Seção SE", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABEN-GO", nome: "Associação Brasileira de Enfermagem - Seção Góias", health: "saudavel", statusCrm: "ativo", mrr: 397 },
  { sigla: "ABEN-SC", nome: "Associação Brasileira de Enfermagem - Seção Santa Catarina", health: "atencao", statusCrm: "ativo", mrr: 600 },
  { sigla: "ABENC-RJ", nome: "Associação Brasileira de Engenheiros Civis", health: "risco", statusCrm: "implantacao", mrr: 297 },
  { sigla: "ABENEPI", nome: "Associação Brasileira de Neurologia e Psiquiatria Infantil e Profissões Afins", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "Abeneuro", nome: "Associação Brasileira de Enfermagem em Neurologia e Neurocirurgia", health: "saudavel", statusCrm: "ativo", mrr: 447 },
  { sigla: "ABENTI", nome: "Ass. Bras. de Enfermagem em Terapia Intensiva Adulto, Pediatrica e Neonatal", health: "saudavel", statusCrm: "ativo", mrr: 500 },
  { sigla: "ABEPEEX", nome: "Associação Brasileira de Estudos em Psicologia do Esporte e do Exercício", health: "saudavel", statusCrm: "ativo", mrr: 397 },
  { sigla: "ABFN", nome: "Associação Brasileira de Famílias Numerosas", health: "atencao", statusCrm: "ativo", mrr: 100 },
  { sigla: "ABH2", nome: "Associação Brasileira do Hidrogênio", health: "saudavel", statusCrm: "ativo", mrr: 970 },
  { sigla: "ABHM", nome: "ABHM - Academia Brasileira de Hipnose Médica", health: "risco", statusCrm: "implantacao", mrr: 657 },
  { sigla: "ABLT", nome: "Associação Brasileira de Locação por Temporada", health: "cancelado", statusCrm: "cancelado", mrr: 657 },
  { sigla: "ABMEC", nome: "Associação Brasileira de Métodos Computaconais em Engenharia", health: "saudavel", statusCrm: "ativo", mrr: 166.67 },
  { sigla: "ABMEN", nome: "Associação Brasileira dos Mentores de Negócios", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "ABMEVEC", nome: "Associação Brasileira de Medicina Veterinária Comportamental", health: "saudavel", statusCrm: "ativo", mrr: 420 },
  { sigla: "ABMLUTO", nome: "Associação Brasileira Multiprofissional sobre o Luto", health: "saudavel", statusCrm: "ativo", mrr: 750 },
  { sigla: "ABOD", nome: "Associação Brasileira de Odontologia Digital", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "ABP", nome: "Associação Brasileira de Psicomotricidade", health: "risco", statusCrm: "implantacao", mrr: 297 },
  { sigla: "ABPBE", nome: "Associação Brasileira de Psicologia Baseada em Evidências", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "ABPP", nome: "Associação Brasileira de Proteção Passiva", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABPsigero", nome: "Associação Brasileira de Psicogerontologia", health: "saudavel", statusCrm: "ativo", mrr: 500 },
  { sigla: "ABQV", nome: "Associação Brasileira de Qualidade de Vida", health: "saudavel", statusCrm: "ativo", mrr: 970 },
  { sigla: "ABRACRIM", nome: "Associação Brasileira dos Advogados Criminalistas", health: "atencao", statusCrm: "ativo", mrr: 1100 },
  { sigla: "ABRADEP", nome: "Academia Brasileira de Direito Eleitoral e Politico", health: "saudavel", statusCrm: "implantacao", mrr: 657 },
  { sigla: "ABRAFIT", nome: "Associação Brasileira de Fisioterapia do Trabalho", health: "saudavel", statusCrm: "ativo", mrr: 327 },
  { sigla: "ABRAHOF", nome: "Associação Brasileira de Harmonização Orofacial", health: "saudavel", statusCrm: "ativo", mrr: 397 },
  { sigla: "ABRAPCORP", nome: "Associação Brasileira de Pesquisadores de Comunicação Organizacional e de Relações Públicas", health: "atencao", statusCrm: "ativo", mrr: 490 },
  { sigla: "ABRAPEE", nome: "Associação Brasileira de Psicologia Escolar e Educacional", health: "atencao", statusCrm: "ativo", mrr: 647 },
  { sigla: "ABRAPEFI", nome: "Associação Brasileira de Perícias Fisioterapêuticas", health: "risco", statusCrm: "ativo", mrr: 200 },
  { sigla: "ABRAPESP", nome: "Associação Brasileira de Psicologia do Esporte", health: "atencao", statusCrm: "ativo", mrr: 930 },
  { sigla: "ABRAPSIT", nome: "Castelum - Associação Brasileira de Psicologia de Tráfego", health: "cancelado", statusCrm: "cancelado", mrr: 327 },
  { sigla: "ABRATENS", nome: "Associação Brasileira de Analistas e Técnicos de Nível Superior do Poder Executivo Federal", health: "saudavel", statusCrm: "ativo", mrr: 397 },
  { sigla: "ABRAVAS", nome: "Associação Brasileira de Veterinários de Animais Selvagens", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABRAVET", nome: "ABRAVET", health: "saudavel", statusCrm: "implantacao", mrr: 367 },
  { sigla: "ABRAZPE", nome: "Associação Brasileira de Zonas de Processamento de Exportação e Zonas Econômicas Especiais", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABS-BA", nome: "Associação Brasileira de Sommeliers", health: "risco", statusCrm: "ativo", mrr: 500 },
  { sigla: "ABSS", nome: "Associação Brasileira de Startups de Saúde", health: "atencao", statusCrm: "ativo", mrr: 300 },
  { sigla: "ABT", nome: "Associação Brasileira de Tanatopraxistas e Tanatologia", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABTER", nome: "Associação Brasileira de Tecnólogos em Radiologia", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ABTOKEN", nome: "Associação Brasileira de Empresas Tokenizadoras e Blockchain", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ACAT", nome: "Associação Carioca dos Advogados Trabalhistas", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ACCP", nome: "Associação Catarinense de Coloproctologia", health: "atencao", statusCrm: "ativo", mrr: 447 },
  { sigla: "ACNMT", nome: "Associação de Criadores de Nelore do Mato Grosso", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "ADCPL", nome: "Associação do Desenvolvimento Comunitário do Povoado Lessa", health: "risco", statusCrm: "ativo", mrr: 147 },
  { sigla: "ADEPRE", nome: "Associação Defensora dos Precatórios do FUNDEF e FUNDEB", health: "risco", statusCrm: "ativo", mrr: 297 },
  { sigla: "ADERON", nome: "Associação dos Deficientes de Rondonópolis – MT", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AEABI-BRA", nome: "Associação de Estudantes Angolanos Bolseiros do INAGBE no Brasil", health: "saudavel", statusCrm: "ativo", mrr: 320 },
  { sigla: "AEAC", nome: "Associação dos Engenheiros e Arquitetos de Cascavel", health: "saudavel", statusCrm: "ativo", mrr: 550 },
  { sigla: "AEACMC", nome: "Associação dos Ex-Alunos do Colégio Militar de Curitiba", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "AEAM", nome: "Associação dos Engenheiros e Arquitetos de Maringá", health: "saudavel", statusCrm: "ativo", mrr: 400 },
  { sigla: "AEDUC", nome: "AEDUC - Associação de Reitores(as), Diretores(as) e Professores(as) de Instituições Educacionais", health: "saudavel", statusCrm: "ativo", mrr: 497 },
  { sigla: "AEIBB", nome: "Associação Estudantil Internacional Brasil Bolívia", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AEXIB", nome: "Associação dos Exibidores Brasileiros de Cinemas de Pequeno e Médio Porte", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AFARGS", nome: "Associação de Farmacêuticos do Rio Grande do Sul", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AGL", nome: "Associação Gaúcha de Laticinistas e Laticínios", health: "saudavel", statusCrm: "ativo", mrr: 220 },
  { sigla: "AGS", nome: "Associação Gaúcha de Startups", health: "atencao", statusCrm: "ativo", mrr: 450 },
  { sigla: "ALMVEST", nome: "Associação Brasileira de Lojistas Multimarcas do Vestuário", health: "cancelado", statusCrm: "cancelado", mrr: 327 },
  { sigla: "AMA", nome: "Associação Maranhense de Administradores", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AMAPOSSE", nome: "Associação de Moradores e Amigos da Posse - Teresópolis RJ", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AMOPRI", nome: "Associação dos Moradores do Condomínio Prive Lago Norte I e II", health: "cancelado", statusCrm: "cancelado", mrr: 147 },
  { sigla: "AMOSAVASSI", nome: "Associação de Moradores da Savassi", health: "cancelado", statusCrm: "cancelado", mrr: 297 },
  { sigla: "AMPD", nome: "Associação Mães e Pais pela Democracia", health: "saudavel", statusCrm: "ativo", mrr: 515 },
  { sigla: "AMSCMA", nome: "Associação de Moradores do Setor de Chácara Morro Azul", health: "saudavel", statusCrm: "ativo", mrr: 180 },
  { sigla: "ANAMMA", nome: "Associação Nacional de Municípios e Meio Ambiente", health: "risco", statusCrm: "ativo", mrr: 297 },
  { sigla: "ANAPM", nome: "Associação Nacional da Advocacia Pública Municipal", health: "saudavel", statusCrm: "ativo", mrr: 400 },
  { sigla: "ANASBB", nome: "Associação Nacional de Defesa dos Direitos dos Aposentados, Funcionários e Pensionistas do Banco do Brasil", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "Andeps", nome: "Associação Nacional da Carreira de Desenvolvimento de Políticas Sociais", health: "saudavel", statusCrm: "ativo", mrr: 347 },
  { sigla: "ANPAGRI", nome: "Associação Nacional dos Pilotos Agrícolas", health: "cancelado", statusCrm: "cancelado", mrr: 597 },
  { sigla: "APAPESP", nome: "Associação dos Procuradores Aposentados do Estado de São Paulo", health: "saudavel", statusCrm: "atencao", mrr: 657 },
  { sigla: "APAPREV", nome: "Associação Paraibana dos Advogados Previdenciaristas", health: "atencao", statusCrm: "ativo", mrr: 200 },
  { sigla: "APDM", nome: "Associação Polo Digital de Manaus", health: "saudavel", statusCrm: "implantacao", mrr: 757 },
  { sigla: "APGBR", nome: "Associação dos Profissionais Genealogistas do Brasil / Softaliza", health: "saudavel", statusCrm: "ativo", mrr: 500 },
  { sigla: "APM-MT", nome: "Associação dos Procuradores Mato Grosso do Centro", health: "saudavel", statusCrm: "ativo", mrr: 400 },
  { sigla: "APQC", nome: "Associação dos Pesquisadores Científicos do Estado de São Paulo", health: "atencao", statusCrm: "ativo", mrr: 950 },
  { sigla: "APRAG", nome: "Associação dos Controladores de Vetores e Pragas Urbanas", health: "risco", statusCrm: "ativo", mrr: 757 },
  { sigla: "APROM - MS", nome: "Associação dos Procuradores Municipais do Estado de Mato Grosso do Sul", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "APROMURN", nome: "Associação dos Procuradores Municipais do Rio Grande do Norte", health: "risco", statusCrm: "ativo", mrr: 297 },
  { sigla: "APRS", nome: "Associação de Psiquiatria do Rio Grande do Sul", health: "saudavel", statusCrm: "implantacao", mrr: 970 },
  { sigla: "ASAPREV", nome: "Associação Sergipana da Advocacia Previdenciarista", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "ASASEPODE", nome: "Associação de Servidores da Área de Segurança, Portadores de Deficiências, do Estado do RS", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ASBAI", nome: "Associação Brasileira de Alergia e Imunologia", health: "atencao", statusCrm: "ativo", mrr: 657 },
  { sigla: "ASBEA-PE", nome: "Associação Brasileira dos Escritórios de Arquitetura - Pernambuco", health: "risco", statusCrm: "ativo", mrr: 397 },
  { sigla: "ASGEM", nome: "Associação Serra Geral de Montanhismo", health: "saudavel", statusCrm: "ativo", mrr: 490 },
  { sigla: "Aspconp-RN", nome: "Associação dos Profissionais de Contabilidade Pública do Rio Grande do Norte", health: "saudavel", statusCrm: "ativo", mrr: 397 },
  { sigla: "ASPER", nome: "Associação dos Produtores de Energia Renováveis", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ASSOGOT", nome: "Associação Gaúcha de Otorrinolaringologia e Cirurgia Cérvico Facial", health: "risco", statusCrm: "ativo", mrr: 800 },
  { sigla: "ASSOPESCA", nome: "Associação dos Pescadores Amapá e Pará", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "ASTOXILATIN", nome: "Associação Latino Americana de Toxicologia Ambiental", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "AZAB", nome: "Associação de Zoológicos e Aquários do Brasil", health: "atencao", statusCrm: "ativo", mrr: 750 },
  { sigla: "Biokybernetik", nome: "Associação Brasileira e Sul Americana de Biokybernetik Smit", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "CATIVA", nome: "Amigos para sempre", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "CBESB", nome: "Centro Brasil-Suécia para Eficiência das Soluções do Biogás, Biofertilizantes e Bioprodutos", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "CBEXS", nome: "Colégio Brasileiro de Executivos em Saúde", health: "saudavel", statusCrm: "ativo", mrr: 970 },
  { sigla: "CPPC", nome: "Corpo de Psicólogos e Psiquiatras Cristãos", health: "saudavel", statusCrm: "ativo", mrr: 757 },
  { sigla: "DSB", nome: "Dança Senior Brasil", health: "saudavel", statusCrm: "ativo", mrr: 800 },
  { sigla: "DUBLAR", nome: "Associação Brasileira de Dubladores", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "Ecotox", nome: "Sociedade Brasileira de Ecotoxicologia", health: "saudavel", statusCrm: "ativo", mrr: 500 },
  { sigla: "ENI", nome: "Associação dos Motoristas, Motociclistas, Taxistas, Parceiros e Comunidade em Geral do RJ", health: "saudavel", statusCrm: "implantacao", mrr: 1070 },
  { sigla: "FEBAB", nome: "Federação Brasileira de Associações de Bibliotecários, Cientistas de Informação e Instituições", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "FEPEME", nome: "Associação de Micro e Pequenas Empresas do Estado do Rio Grande do Sul", health: "risco", statusCrm: "ativo", mrr: 297 },
  { sigla: "FJS", nome: "Fundação Jose Silveira", health: "saudavel", statusCrm: "ativo", mrr: 450 },
  { sigla: "Fúria Jovem", nome: "Fúria Jovem do Botafogo", health: "atencao", statusCrm: "ativo", mrr: 200 },
  { sigla: "IAMAT", nome: "Instituto dos Advogados Matogrossenses", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "IGAS", nome: "Instituto Gaúcho de Asseio e Serviços", health: "atencao", statusCrm: "ativo", mrr: 1000 },
  { sigla: "IMD", nome: "Instituto dos Sonhos", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "INAPE", nome: "INAPE", health: "cancelado", statusCrm: "cancelado", mrr: null },
  { sigla: "LATS", nome: "Latin American Thyroid Society", health: "risco", statusCrm: "ativo", mrr: 800 },
  { sigla: "Mauatur", nome: "Associação Turística e Comercial da Região de Visconde de Mauá", health: "risco", statusCrm: "implantacao", mrr: 297 },
  { sigla: "OPJ", nome: "Ordem dos Peritos Judiciais", health: "saudavel", statusCrm: "ativo", mrr: 757 },
  { sigla: "PROBR-NE", nome: "ProBrasil - Nordeste", health: "saudavel", statusCrm: "implantacao", mrr: 297 },
  { sigla: "PROBR-SP", nome: "ProBrasil - São Paulo", health: "saudavel", statusCrm: "implantacao", mrr: 297 },
  { sigla: "PROLIFE", nome: "Prolife - Desenvolvimento Psicológico Ltda", health: "saudavel", statusCrm: "implantacao", mrr: 297 },
  { sigla: "QCB", nome: "Associação Quaternity Clubs Brasil", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "Quilombo Jacarandá", nome: "Associação Quilombola do Jacarandá", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "RBRAS", nome: "Região Brasileira da Sociedade Internacional de Biometria", health: "saudavel", statusCrm: "ativo", mrr: 650 },
  { sigla: "REDE CONSTRUMASTER", nome: "Rede Construmaster", health: "cancelado", statusCrm: "cancelado", mrr: 657 },
  { sigla: "RedIF", nome: null, health: "saudavel", statusCrm: "ativo", mrr: 450 },
  { sigla: "RIB-CE", nome: "Registro de Imóveis do Brasil - Seção Ceará", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "SAB", nome: "Sociedade Astronômica Brasileira", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "SBAP", nome: "Sociedade Brasileira de Administração Pública", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "SBB", nome: "Sociedade Brasileira de Botânica", health: "saudavel", statusCrm: "ativo", mrr: 1340 },
  { sigla: "SBCEC", nome: "Sociedade Brasileira de Circulação Extracorpórea", health: "risco", statusCrm: "ativo", mrr: 1250 },
  { sigla: "SBCS", nome: "Sociedade Brasileira de Ciências do Solo", health: "saudavel", statusCrm: "ativo", mrr: 650 },
  { sigla: "SBEB", nome: "Sociedade Brasileira de Engenharia Biomédica", health: "saudavel", statusCrm: "ativo", mrr: 1092 },
  { sigla: "SBEnQ", nome: "Sociedade Brasileira de Ensino de Química", health: "saudavel", statusCrm: "ativo", mrr: 800 },
  { sigla: "SBI-ICT", nome: "Sociedade Brasileira de Ictiologia", health: "risco", statusCrm: "ativo", mrr: 790 },
  { sigla: "SBI-INF", nome: "Sociedade Brasileira de Infectologia", health: "saudavel", statusCrm: "ativo", mrr: 970 },
  { sigla: "SBIA", nome: "Sociedade Brasileira de Inteligência Artificial", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "SBIS", nome: "Sociedade Brasileira de Informática em Saúde", health: "atencao", statusCrm: "ativo", mrr: 819.99 },
  { sigla: "SBMAC", nome: "Sociedade Brasileira de Matemática Computacional", health: "saudavel", statusCrm: "ativo", mrr: 540 },
  { sigla: "SBMT", nome: "Sociedade Brasileira de Medicina Tropical", health: "saudavel", statusCrm: "ativo", mrr: 550 },
  { sigla: "SBMZ", nome: "Sociedade Brasileira de Mastozoologia", health: "saudavel", statusCrm: "ativo", mrr: 750 },
  { sigla: "SBNI", nome: "Sociedade Brasileira de Neurologia Infantil", health: "saudavel", statusCrm: "ativo", mrr: 1070 },
  { sigla: "SBNR", nome: "Sociedade Brasileira de Neurorradiologia Diagnóstica e Terapêutica", health: "saudavel", statusCrm: "ativo", mrr: 640 },
  { sigla: "SBOC", nome: "Sociedade Brasileira de Oncologia Clínica", health: "saudavel", statusCrm: "ativo", mrr: 970 },
  { sigla: "SBPH", nome: "Sociedade Brasileira de Psicologia Hospitalar", health: "saudavel", statusCrm: "ativo", mrr: 1390 },
  { sigla: "SBTOX", nome: "Sociedade Brasileira de Toxicologia", health: "saudavel", statusCrm: "ativo", mrr: 650 },
  { sigla: "SE&PQ", nome: "Sociedade de Estudos e Pesquisa Qualitativos", health: "atencao", statusCrm: "ativo", mrr: 397 },
  { sigla: "SEANOR", nome: "Sindicato dos Escreventes e Auxiliares Notariais e Registrais do Estado de São Paulo", health: "saudavel", statusCrm: "ativo", mrr: 657 },
  { sigla: "SINEBRAS", nome: "Sindicato de Escritores do Brasil", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "SINPRA", nome: "Sindicato dos Produtores do Acará", health: "atencao", statusCrm: "ativo", mrr: 297 },
  { sigla: "SOBRAC", nome: "Associação Brasileira de Climatério", health: "saudavel", statusCrm: "ativo", mrr: 800 },
  { sigla: "SOBRAEP", nome: "Associação Brasileira de Eletrônica de Potência", health: "saudavel", statusCrm: "ativo", mrr: 100 },
  { sigla: "SOTER", nome: "Sociedade de Teologia e Ciências da Religião", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "SRMG", nome: "Sociedade de Radiologia de Minas Gerais", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "TWRA", nome: "Tropical Water Research Alliance", health: "saudavel", statusCrm: "ativo", mrr: 327 },
  { sigla: "UCIB", nome: "União das Controladorias Internas do Estado da Bahia", health: "saudavel", statusCrm: "ativo", mrr: 297 },
  { sigla: "UNILIM", nome: "Associação dos Universitários de Limoeiro do Norte", health: "risco", statusCrm: "ativo", mrr: 200 },
  { sigla: "WANS", nome: "World Academy of Neurological Surgery", health: "atencao", statusCrm: "ativo", mrr: 0.1 },
  { sigla: "ZOO MELHOR", nome: "Associação Zoo Melhor", health: "atencao", statusCrm: "ativo", mrr: 297 },
];

// --- CS Hub: tabela `client_events` (congressos, jornadas, simpósios etc.) ---
const EVENTS_CRM = [
  { id: "9a17d596", sigla: null, associacao: null, nome: "UFJF - Conferência", shortName: "LATAM-SHM 2028", edicao: null, ano: 2027, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "a4e7f90e", sigla: "ABE", associacao: "Associação Brasileira de Estatística", nome: "VIII Latin American Meeting on Bayesian Statistics (COBAL/EBEB)", shortName: "COBAL 2027", edicao: "VIII", ano: 2027, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "45141c9b", sigla: "SBCEC", associacao: "Sociedade Brasileira de Circulação Extracorpórea", nome: "43º Congresso Brasileiro de Circulação Extracorpórea", shortName: "SBCEC 2026", edicao: "43º", ano: 2026, tipo: "congresso", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "fa6a9163", sigla: null, associacao: null, nome: "IV Simpósio Gaúcho de Segurança Sanitária de Alimentos", shortName: "Bcontrol", edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "d217135d", sigla: null, associacao: null, nome: "ICOVP 2027 — Congresso Internacional de Vibração (UnB)", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "a9e356af", sigla: null, associacao: null, nome: "35º Encontro Anual da Compós", shortName: "COMPÓS 2026", edicao: "35º", ano: 2026, tipo: "encontro", status: "inscricoes_abertas", temSite: true, siteUrl: "https://compos2026.softaliza.com.br", cidade: "Natal", estado: "RN" },
  { id: "ca300fd7", sigla: "SBEB", associacao: "Sociedade Brasileira de Engenharia Biomédica", nome: "XXX Congresso Brasileiro de Engenharia Biomédica", shortName: "CBEB 2026", edicao: "XXX", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://cbeb.org.br/", cidade: null, estado: null },
  { id: "b65f6a4b", sigla: null, associacao: null, nome: "II Congresso Internacional de Práticas em Terapia do Esquema", shortName: "ConEsquemas 2026", edicao: "II", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://conesquemas.com.br", cidade: "Recife", estado: "PE" },
  { id: "d16b804b", sigla: null, associacao: null, nome: "Congresso Brasileiro de Estruturas Metálicas e Mistas", shortName: "CBEMM 2026", edicao: "II", ano: 2026, tipo: "congresso", status: "encerrado", temSite: true, siteUrl: "https://cbemm.com.br", cidade: "Maringá", estado: "PR" },
  { id: "0f3e60d8", sigla: null, associacao: null, nome: "87ª Semana Brasileira de Enfermagem", shortName: "ABEn 2026", edicao: "87ª", ano: 2026, tipo: "encontro", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "2bd2cb6f", sigla: "CPPC", associacao: "Corpo de Psicólogos e Psiquiatras Cristãos", nome: "XXIII Congresso Nacional CPPC", shortName: "CPPC 2026", edicao: "XXIII", ano: 2026, tipo: "congresso", status: "encerrado", temSite: true, siteUrl: "https://congressonacionalcppc.com.br", cidade: "Lauro de Freitas", estado: "BA" },
  { id: "e5f92c2e", sigla: null, associacao: null, nome: "ASIS Latin American & Caribbean Conference 2026", shortName: "ASIS 2026", edicao: null, ano: 2026, tipo: "congresso", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "a19a0a41", sigla: "SBB", associacao: "Sociedade Brasileira de Botânica", nome: "IV Encontro Regional de Botânicos do Norte", shortName: "ERBot Norte 2026", edicao: "IV", ano: 2026, tipo: "encontro", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "f8e81d71", sigla: "ABRAVAS", associacao: "Associação Brasileira de Veterinários de Animais Selvagens", nome: "XXXIV Encontro e XXVIII Congresso da ABRAVAS", shortName: "ABRAVAS 2026", edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://congressoabravas.com.br/", cidade: "Belo Horizonte", estado: "MG" },
  { id: "c0bf0b5b", sigla: "ABRAPCORP", associacao: "Associação Brasileira de Pesquisadores de Comunicação Organizacional e de Relações Públicas", nome: "XX Congresso Abrapcorp", shortName: "ABRAPCORP 2026", edicao: "XX", ano: 2026, tipo: "congresso", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "0c2de9dc", sigla: "ABOD", associacao: "Associação Brasileira de Odontologia Digital", nome: "10º Meeting ABOD", shortName: "ABOD 2026", edicao: "10º", ano: 2026, tipo: "encontro", status: "cancelado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "492245f4", sigla: null, associacao: null, nome: "18th World Congress on Parasitic Plants", shortName: "WCPP 2026", edicao: "18th", ano: 2026, tipo: "congresso", status: "cancelado", temSite: true, siteUrl: "https://18wcppbrasil.com.br", cidade: "São Sebastião", estado: "SP" },
  { id: "8161b428", sigla: "SBMZ", associacao: "Sociedade Brasileira de Mastozoologia", nome: "Rede SBMz", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "c7bec396", sigla: null, associacao: "Associação Brasileira de Psicogerontologia", nome: "Congresso Brasileiro de Psicogerontologia", shortName: "Psicogerontologia 2026", edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "5433315a", sigla: "ABEClin", associacao: "Associação Brasileira de Engenharia Clínica", nome: "Congresso Brasileiro de Engenharia Clínica", shortName: "ABEClin 2026", edicao: null, ano: 2026, tipo: "congresso", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "5a11b46c", sigla: null, associacao: null, nome: "III Congresso Internacional de Mulheres STEAM", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "f0dbd805", sigla: "AZAB", associacao: "Associação de Zoológicos e Aquários do Brasil", nome: "49º Congresso da Associação de Zoológicos e Aquários do Brasil", shortName: "AZAB 2026", edicao: "49º", ano: 2026, tipo: "congresso", status: "encerrado", temSite: true, siteUrl: "https://49congressoazab.softaliza.com.br", cidade: "Campo Grande", estado: "MS" },
  { id: "fd2a2c66", sigla: "SBTOX", associacao: "Sociedade Brasileira de Toxicologia", nome: "XXIV Congresso Brasileiro de Toxicologia", shortName: "CBTOX 2026", edicao: "XXIV", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://cbtox.com.br", cidade: null, estado: null },
  { id: "88117db6", sigla: null, associacao: null, nome: "Workshop em anestesia de animais selvagens", shortName: "Anestesia 2026", edicao: null, ano: 2026, tipo: "workshop", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "2e993299", sigla: null, associacao: null, nome: "II Congresso & V Workshop de Reabilitação, Monitoramento e Conservação da Fauna Silvestre", shortName: "WAITA 2026", edicao: "II", ano: 2026, tipo: "congresso", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "ee9aec4b", sigla: null, associacao: null, nome: "Agência Flap", shortName: "Porão na Roda", edicao: null, ano: 2026, tipo: "congresso", status: "site_em_desenvolvimento", temSite: true, siteUrl: "https://poraonaroda.softaliza.com.br/", cidade: null, estado: null },
  { id: "6d0d614e", sigla: "SBB", associacao: "Sociedade Brasileira de Botânica", nome: "46º Encontro Regional de Botânicos", shortName: "ERBot 2026", edicao: "46º", ano: 2026, tipo: "encontro", status: "encerrado", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "6c507b79", sigla: null, associacao: null, nome: "IV Jornada de Avaliação Psicológica do Recife", shortName: "Java Psic", edicao: "IV", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://www.javapsic.com.br/", cidade: null, estado: null },
  { id: "e651166f", sigla: null, associacao: null, nome: "XVI Jornada de Atualização em Neurologia", shortName: "Jornada PUC", edicao: "XVI", ano: 2026, tipo: "jornada", status: "inscricoes_abertas", temSite: true, siteUrl: "https://jornadapuc2026.softaliza.com.br/", cidade: null, estado: null },
  { id: "e4ee895f", sigla: null, associacao: null, nome: "Jornada de Terapia do Esquema", shortName: null, edicao: "2ª", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: "Fortaleza", estado: "CE" },
  { id: "7fb45219", sigla: null, associacao: null, nome: "SINCOL", shortName: "SINCOL", edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: true, siteUrl: "https://sincol2026.softaliza.com.br/", cidade: null, estado: null },
  { id: "8f4f9895", sigla: "SBAP", associacao: "Sociedade Brasileira de Administração Pública", nome: "Encontro Brasileiro de Administração Pública", shortName: "SBAP 2026", edicao: null, ano: 2026, tipo: "encontro", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "0e792d8d", sigla: "SBB", associacao: "Sociedade Brasileira de Botânica", nome: "IV Jornada Rio-São Paulo de Botânica", shortName: "Jornada Botânica 2026", edicao: "IV", ano: 2026, tipo: "jornada", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "bcde7bbb", sigla: null, associacao: null, nome: "XII Congresso da Associação Brasileira de Rorschach e Métodos Projetivos", shortName: "ASBRo 2026", edicao: "XII", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://asbro2026.softaliza.com.br", cidade: "Fortaleza", estado: "CE" },
  { id: "9b7beee8", sigla: "ABH2", associacao: "Associação Brasileira do Hidrogênio", nome: "1º Seminário Brasileiro do Hidrogênio", shortName: "ABH2 2026", edicao: "1º", ano: 2026, tipo: "seminario", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "529d224a", sigla: "SBMZ", associacao: "Sociedade Brasileira de Mastozoologia", nome: "Rede SBMz", shortName: "SBMz 2026", edicao: null, ano: 2026, tipo: "encontro", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "3d66821a", sigla: null, associacao: null, nome: "1º Simpósio da OHDSI na América Latina", shortName: "1º Simpósio da OHDSI", edicao: null, ano: 2026, tipo: "simposio", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "ebd311fb", sigla: "SBCS", associacao: "Sociedade Brasileira de Ciências do Solo", nome: "IX Simpósio Mineiro de Ciência do Solo", shortName: "SBCS 2026", edicao: "IX", ano: 2026, tipo: "simposio", status: "inscricoes_abertas", temSite: true, siteUrl: "https://smcs2026.softaliza.com.br/", cidade: null, estado: null },
  { id: "e025bd4c", sigla: "ABE", associacao: "Associação Brasileira de Estatística", nome: "26º Simpósio Nacional de Probabilidade e Estatística", shortName: "SINAPE 2026", edicao: "26º", ano: 2026, tipo: "simposio", status: "inscricoes_abertas", temSite: true, siteUrl: "https://sinape2026.com.br", cidade: "Gramado", estado: "RS" },
  { id: "562e7564", sigla: "ABRAPEE", associacao: "Associação Brasileira de Psicologia Escolar e Educacional", nome: "XVII Congresso Nacional de Psicologia Escolar e Educacional - CONPE", shortName: "CONPE 2026", edicao: "XVII", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://conpe2026abrapee.softaliza.com.br/", cidade: null, estado: null },
  { id: "bc9b84e3", sigla: null, associacao: null, nome: "III ConNorteNordesteTCC", shortName: "ConNorteNordeste 2026", edicao: "III", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://connortenordestetcc.com.br/", cidade: null, estado: null },
  { id: "7c382551", sigla: null, associacao: null, nome: "I Congresso Internacional TraumaClinic", shortName: "TraumaClinic 2026", edicao: "I", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "baff9f29", sigla: "SBB", associacao: "Sociedade Brasileira de Botânica", nome: "76º Congresso Nacional de Botânica", shortName: "CNBot 2026", edicao: "76º", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://76cnbot.softaliza.com.br", cidade: "Campo Grande", estado: "MS" },
  { id: "531fb099", sigla: null, associacao: null, nome: "CIPEEX 2026", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "4f48e7bc", sigla: null, associacao: null, nome: "SEPOC 2026", shortName: "SEPOC 2026", edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://sepoc.com.br/", cidade: null, estado: null },
  { id: "aca8d67d", sigla: "RBRAS", associacao: "Região Brasileira da Sociedade Internacional de Biometria", nome: "70º RBRaS", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://70rbras.softaliza.com.br/", cidade: null, estado: null },
  { id: "16ccce40", sigla: null, associacao: null, nome: "XLIX RASAB", shortName: "RASAB 2026", edicao: "XLIX", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "9fa73a2d", sigla: "ABE", associacao: "Associação Brasileira de Estatística", nome: "10th Conference of the International Association for Computerized Adaptive Testing", shortName: "CAT 2026", edicao: "10th", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "30662ca1", sigla: "ABMEC", associacao: "Associação Brasileira de Métodos Computaconais em Engenharia", nome: "XLVII CILAMCE", shortName: "CILAMCE 2026", edicao: "XLVII", ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: "https://cilamce.com.br/", cidade: null, estado: null },
  { id: "c9c2f55b", sigla: "ABEPEEX", associacao: "Associação Brasileira de Estudos em Psicologia do Esporte e do Exercício", nome: "CONBIPE 2026", shortName: "CONBIPE 2026", edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "9e6e999b", sigla: null, associacao: null, nome: "GEORS 2026 — Seminário de Engenharia Geotécnica do RS", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "c40721e6", sigla: null, associacao: null, nome: "XVIII Encontro da Regional São Paulo da Abrapso", shortName: "ABRAPSO SP 2026", edicao: "XVIII", ano: 2026, tipo: "encontro", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "40ec2217", sigla: null, associacao: null, nome: "SOBER Nordeste - Congresso", shortName: null, edicao: null, ano: 2026, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "5c70b8ee", sigla: null, associacao: null, nome: "Conneuropsi", shortName: "Conneuropsi", edicao: null, ano: 2026, tipo: "congresso", status: "encerrado", temSite: true, siteUrl: "https://conneuropsi.com.br/", cidade: null, estado: null },
  { id: "a3a599d1", sigla: "ABE", associacao: "Associação Brasileira de Estatística", nome: "VIII Latin American Meeting on Bayesian Statistics (COBAL) e XVIII EBEB", shortName: "COBAL", edicao: null, ano: 2026, tipo: "congresso", status: "inscricoes_abertas", temSite: true, siteUrl: null, cidade: null, estado: null },
  { id: "a63d45c0", sigla: null, associacao: null, nome: "COBEP", shortName: "COBEP", edicao: null, ano: null, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "6e0763b1", sigla: null, associacao: null, nome: "RISCO", shortName: "RISCO", edicao: null, ano: null, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
  { id: "1e2e2b92", sigla: "SBEnQ", associacao: "Sociedade Brasileira de Ensino de Química", nome: "SBEnQ - Evento", shortName: "SBEnQ", edicao: null, ano: null, tipo: "congresso", status: "planejamento", temSite: false, siteUrl: null, cidade: null, estado: null },
];

// --- Planilha de inventário de sites (Google Sheets) ---
// evento: true = site de evento/congresso · false = site institucional da associação
const SITE_INVENTORY = [
  { sigla: "CCM", nome: "Hepatologia do Milênio 2024", area: "Saúde", site: "https://www.hepatologiadomilenio.com.br/", evento: true },
  { sigla: "SBB", nome: "74º Congresso Nacional de Botânica", area: "Botânica", site: "https://74cnbot.softaliza.com.br/", evento: true },
  { sigla: "RBRAS", nome: "Reunião Anual da Região Brasileira da Sociedade Internacional de Biometria", area: "Estatística", site: "https://69rbras21seagro.com.br/", evento: true },
  { sigla: "ABE", nome: "Associação Brasileira de Estatística", area: "Estatística", site: "https://www.redeabe.org.br/", evento: false },
  { sigla: "WANS", nome: "World Academy of Neurological Surgery", area: "Médica", site: "https://worldacademynsurg.org/", evento: false },
  { sigla: "ABMEC", nome: "Associação Brasileira de Métodos Computacionais em Engenharia", area: "Engenharia", site: "https://abmec.org.br/", evento: false },
  { sigla: "ABEN-SC", nome: "Associação Brasileira de Enfermagem - Seção Santa Catarina", area: "Enfermagem", site: "https://aben-sc.softaliza.com.br/", evento: false },
  { sigla: "SBNR", nome: "Sociedade Brasileira de Neurorradiologia Diagnóstica e Terapêutica", area: "Médica", site: "https://sbnr.org.br/", evento: false },
  { sigla: "SBPH", nome: "Sociedade Brasileira de Psicologia Hospitalar", area: "Psicologia", site: "https://sbph.org.br/", evento: false },
  { sigla: "Ecotox", nome: "Sociedade Brasileira de Ecotoxicologia", area: "Ambiental", site: "https://ecotoxbrasil.org.br/", evento: false },
  { sigla: "SOBRAC", nome: "Associação Brasileira de Climatério", area: "Médica", site: "https://sobrac.softaliza.com.br/", evento: false },
  { sigla: "SBCS", nome: "Sociedade Brasileira de Ciências do Solo", area: "Ciência do Solo", site: "https://www.sbcs.org.br/", evento: false },
  { sigla: "AZAB", nome: "47º Congresso da Associação de Zoológicos e Aquários do Brasil", area: "Zoológico", site: "https://47congressoazab.softaliza.com.br/", evento: true },
  { sigla: "APQC", nome: "Associação dos Pesquisadores Científicos do Estado de São Paulo", area: "Pesquisadores", site: "https://apqc.org.br/", evento: false },
  { sigla: "INAPE", nome: "Instituto Nacional de Apoio a Portadores de Espondiloartrites", area: "Saúde", site: "https://inape.softaliza.com.br/", evento: false },
  { sigla: "SBIS", nome: "Sociedade Brasileira de Informática em Saúde", area: "Médica", site: "https://sbis.org.br/", evento: false },
  { sigla: "LATS", nome: "Latin American Thyroid Society", area: "Médica", site: "https://lats.org/", evento: false },
  { sigla: "SBMZ", nome: "Sociedade Brasileira de Mastozoologia", area: "Ciências Biológicas", site: "https://sbmz.org/", evento: false },
  { sigla: "ABPsigero", nome: "I Congresso Brasileiro de Psicogerontologia", area: "Psicologia", site: "https://congressodepsicogerontologia.softaliza.com.br/", evento: true },
  { sigla: "ASTOXILATIN", nome: "Associação Latino Americana de Toxicologia Ambiental", area: "Toxicologia", site: "https://astoxilatin.softaliza.com.br/", evento: false },
  { sigla: "ASTOXILATIN", nome: "IV Congresso Latino-Americano de Toxicologia Clínico-Laboratorial", area: "Toxicologia", site: "https://toxilatin2025.softaliza.com.br/", evento: true },
  { sigla: "ABToken", nome: "Associação Brasileira das Empresas Tokenizadoras de Ativos", area: "Tecnologia", site: "https://abtoken.com.br/", evento: false },
  { sigla: "ABEN-GO", nome: "Associação Brasileira de Enfermagem - Seção Góias", area: "Enfermagem", site: "https://abengoias.org.br/", evento: false },
  { sigla: "AMPD", nome: "Associação Mães e Pais pela Democracia", area: "Política", site: "https://ampd.softaliza.com.br/", evento: false },
  { sigla: "SBI", nome: "Sociedade Brasileira de Ictiologia", area: "Biologia", site: "https://sbi.softaliza.com.br/", evento: false },
  { sigla: "FEBRAP", nome: "14º Congresso Iberoamericano de Psicodrama", area: "Psicologia", site: "https://14iberoamericanopsicodrama.softaliza.com.br/", evento: true },
  { sigla: "ABN-RJ", nome: "Meeting the Experts Neurology", area: "Médica", site: "https://meetingneurology.com.br/", evento: true },
  { sigla: "SBB", nome: "Sociedade Botânica do Brasil", area: "Botânica", site: "https://www.botanica.org.br/", evento: false },
  { sigla: "COMPOS", nome: "33º Encontro Anual da Compós", area: "Artes", site: "https://compos2025.softaliza.com.br", evento: true },
  { sigla: "SBB", nome: "75º Congresso Nacional de Botânica", area: "Botânica", site: "https://75cnbot.softaliza.com.br/", evento: true },
  { sigla: "SBCS", nome: "XXI Reunião Brasileira de Manejo e Conservação do Solo e da Água e VIII Simpósio Mineiro de Ciência do Solo", area: "Ciência do Solo", site: "https://rbmcsa.softaliza.com.br/", evento: true },
  { sigla: "UPE", nome: "III Workshop em Biologia Celular e Molecular", area: "Biologia", site: "https://3-iwcmb.softaliza.com.br/", evento: true },
  { sigla: "UFSM", nome: "Seminar on Power Electronics and Control, SEPOC", area: "Tecnologia", site: "https://sepoc.com.br/", evento: true },
  { sigla: "UNIMED", nome: "Unimed Class", area: "Saúde", site: "https://unimedclass.com.br/", evento: true },
  { sigla: "RDL", nome: "Rede Brasileira Direito e Literatura", area: "Advocacia", site: "https://rdl.softaliza.com.br/", evento: false },
  { sigla: "ITA", nome: "Congresso Internacional de Mulheres em STEAM", area: "Tecnologia", site: "https://congressomulheresemsteam.com.br/", evento: true },
  { sigla: "ABRAPCORP", nome: "Associação Brasileira de Pesquisadores de Comunicação Organizacional e de Relações Públicas", area: "Pesquisadores", site: "https://abrapcorp.org.br/", evento: false },
  { sigla: "RBRAS", nome: "VII Workshop em Análise de Sobrevivência e Aplicações", area: "Estatística", site: "http://viiwasa.softaliza.com.br/", evento: true },
  { sigla: "SBCS", nome: "Congresso Brasileiro de Ciência do Solo", area: "Ciência do Solo", site: "https://solos2025.com.br/", evento: true },
  { sigla: "ABPsigero", nome: "Associação Brasileira de Psicogerontologia", area: "Psicologia", site: "https://psicogerontologia.softaliza.com.br/", evento: false },
  { sigla: "VTS", nome: "Workshop on Communication Networks and Power Systems", area: "Comunicação", site: "https://wcnps2024.softaliza.com.br/login/", evento: true },
  { sigla: "CCM", nome: "XIV Jornada de Atualização em Neurologia do Hospital São Lucas da PUCRS", area: "Saúde", site: "https://jornadaneuro2024.com.br/", evento: true },
  { sigla: "LabQEE", nome: "Conferência Brasileira Sobre Qualidade da Energia Elétrica", area: "Elétrica", site: "https://cbqee2025.softaliza.com.br/", evento: true },
  { sigla: "FEBRAP", nome: "24º Congresso Brasileiro de Psicodrama", area: "Psicologia", site: "https://24cbp2iagp.softaliza.com.br/", evento: true },
  { sigla: "CPPC", nome: "Corpo de Psicólogos e Psiquiatras Cristão", area: "Psicologia", site: "https://cppc.softaliza.com.br/", evento: false },
  { sigla: "CRPP", nome: "Encontro Paranaense de Psicologia", area: "Psicologia", site: "https://epp.softaliza.com.br/", evento: true },
  { sigla: "ELO EVENTOS", nome: "Congresso Internacional SOBREXP", area: "Saúde", site: "https://sobrexp2024.softaliza.com.br/", evento: true },
  { sigla: "CSQA", nome: "Congresso de Qualidade e Segurança de Alimentos", area: "Alimentos", site: "https://csqa2024.softaliza.com.br/", evento: true },
  { sigla: "MTCN", nome: "Portos & Costas Brasil 2025", area: "Portuária", site: "https://portosecostas.com.br/", evento: true },
  { sigla: "ABE", nome: "XIX Escola de Modelos de Regressão e V Encontro Paraibano de Estatística", area: "Estatística", site: "https://xixemrvepbest.softaliza.com.br/", evento: true },
  { sigla: "CCM", nome: "Atenção Primária à Saúde - LABS", area: "Saúde", site: "https://restrito.apslabs.com.br/", evento: true },

  // --- Novos links encontrados na planilha (análise de 13/07/2026) ---
  { sigla: "SOBRAEP", nome: "Associação Brasileira de Eletrônica de Potência", area: "Eletrônica", site: "https://sobraep.softaliza.com.br/", evento: false },
  { sigla: "ABEE-MT", nome: "Associação Brasileira de Engenheiros Eletricistas de Mato Grosso", area: "Elétrica", site: "https://abeemt.org.br/", evento: false },
  { sigla: "OPJ", nome: "Ordem dos Peritos Judiciais", area: "Advocacia", site: "https://opj.org.br/", evento: false },
  { sigla: "CBESB", nome: "Biogas Solutions Research Center", area: "Química", site: "https://cbesbiogas.softaliza.com.br/", evento: false },
  { sigla: "SE&PQ", nome: "Sociedade de Estudos e Pesquisa Qualitativos", area: "Pesquisa", site: "https://sepq.softaliza.com.br/", evento: false },
  { sigla: "APRAG", nome: "Associação dos Controladores de Vetores e Pragas Urbanas", area: "Pragas", site: "https://www.aprag.org.br/", evento: false },

  { sigla: null, nome: "21ª Escola de Séries Temporais e Econometria (ESTE)", area: "Educação", site: "https://este2025.softaliza.com.br/", evento: true },
  { sigla: "TOXFORENSE", nome: "I Simpósio Internacional de Toxicologia Forense", area: "Toxicologia", site: "https://simposiotoxforense2025.softaliza.com.br/", evento: true },
  { sigla: null, nome: "Congresso Multidisciplinar de Saúde e Bem-estar (COMSEBE)", area: "Saúde", site: "https://comsebe.softaliza.com.br/", evento: true },
  { sigla: null, nome: "Seminário Educação, Informação e Saúde: Proteções Contra à Desinformação (SEISDESIN)", area: "Saúde", site: "https://seisdesin2025.softaliza.com.br/", evento: true },
  { sigla: "RedIF", nome: "Red Iberoamericana de Pharmacometria - RedIf", area: "Educação", site: "https://www.redifar.org/?lang=pt", evento: true },
  { sigla: "HMC", nome: "Curso: Sistema de Saúde Alemão (2025)", area: "Saúde", site: "https://alemanha25.hmcourses.com.br/", evento: true },
  { sigla: "HMC", nome: "Curso: Sistema de Saúde Alemão (2024)", area: "Saúde", site: "https://alemanha24.hmcourses.com.br/", evento: true },
  { sigla: "HMC", nome: "Curso: Sistema de Saúde Espanhol", area: "Saúde", site: "https://espanha25.hmcourses.com.br/", evento: true },
  { sigla: "HMC", nome: "Curso: Sistema de Saúde de Londres", area: "Saúde", site: "https://londres23.hmcourses.com.br/", evento: true },
];

// --- Projetos Vercel já confirmados (institucionais de associação) ---
const VERCEL_ASSOC = {
  ABIH: { project: "sites-abih", dominio: "abih-pb.com.br/associados/" },
  SBNI: { project: "sites-sbni", dominio: null },
  APDM: { project: "sites-polodigital", dominio: null },
  APAPESP: { project: "sites-apapesp", dominio: null },
  AATESP: { project: "sites-aatesp", dominio: "aatesp.softaliza.com.br/arteterapia" },
  ENI: { project: "sites-eni", dominio: "eni.softaliza.com.br" },
  WANS: { project: "sites-wans", dominio: null },
  ABRAVET: { project: "sites-abravet", dominio: null },
  AATP: { project: "sites-aatp", dominio: "aatp.softaliza.com.br" },
};

// --- Projetos Vercel já confirmados (sites de evento/congresso), por id do evento ---
const VERCEL_EVENT = {
  "7fb45219": { project: "sites-sincol2026" },
  e651166f: { project: "sites-jornadapuc2026" },
  "6c507b79": { project: "sites-javapsic" },
  "9e6e999b": { project: "sites-geors", dominio: "geors2026.softaliza.com.br" },
  a63d45c0: { project: "sites-cobep2027" },
  c7bec396: { project: "sites-iipsicogerontologia", dominio: "congressopsicogerontologia2026.softaliza.com.br" },
};

// --- Nível manual (A/B/C) já classificado — a maioria ainda está pendente ---
const NIVEL_OVERRIDE = {
  AATP: "B",
};

// --- Pastas locais em sites-ajustes = ainda em ajuste manual (WordPress) ---
// Associações com site institucional próprio sendo ajustado localmente:
const LOCAL_FOLDER_ASSOC = {
  ABMEVEC: "abmevec",
  ABPsigero: "abpsigero",
  ABRAPEE: "abrapee",
  ABRAVAS: "abravas",
  AZAB: "azab",
  CBESB: "cbesb",
  CPPC: "cppc",
  OPJ: "opj",
  SBCS: "sbcs",
  SBEB: "sbeb",
  SBPH: "sbph",
  SBTOX: "sbtox",
  "SE&PQ": "seepq",
};

// --- Sites de evento sendo ajustados localmente, por id do evento em EVENTS_CRM ---
const LOCAL_FOLDER_EVENT = {
  baff9f29: "76cnbot",
  bcde7bbb: "asbro",
  fd2a2c66: "cbtox",
  "30662ca1": "cilamce",
  a4e7f90e: "cobal27",
  a9e356af: "compos",
  b65f6a4b: "conesquemas",
  "5c70b8ee": "conneuropsi",
  bc9b84e3: "connortenordeste",
  "562e7564": "conpe",
  e4ee895f: "jornada-terapia-esquema",
  ee9aec4b: "rodaporao",
  "4f48e7bc": "sepoc",
  ebd311fb: "simposiomineiro",
  f0dbd805: "azab",
  f8e81d71: "abravas",
  "2bd2cb6f": "cppc",
  ca300fd7: "sbeb",
};
